language: ruby
cache:
  - bundler
sudo: required
branches:
  only:
  - master
before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
script:
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
  - travis_retry bundle exec rake test
