language: ruby
rvm:
  - 2.6
  - 2.5
  - 2.4
  - 2.3
cache:
  - bundler
sudo: required
services:
  - mongodb
branches:
  only:
  - master
  - master
before_script:
  - git config --global user.email "travis@travis.ci"
  - git config --global user.name "Travis CI"
script:
  - bundle exec overcommit --sign
  - bundle exec overcommit --run
  - travis_retry bundle exec rake test
