name: Continuous Integration
on:
  pull_request:
    branches:
      - master
      - cqm_validators_2_x

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.6, 2.5]
        mongodb-version: [4.0.18, 4.4]

    steps:
    - uses: actions/checkout@master
    - name: Use Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run overcommit
      run: |
        bundle exec overcommit --sign
        bundle exec overcommit --run
    - name: Run tests
      run: bundle exec rake
    - name: Codecov action
      uses: codecov/codecov-action@v1.2.1
    # - name: Upload to codecov
    #   run: bash <(curl -s https://codecov.io/bash)
    # - name: Upload coverage to Codecov example
    #   uses: codecov/codecov-action@v1
    #   with:
    #     files: ./coverage1.xml,./coverage2.xml
    #     directory: ./coverage/reports/
    #     name: codecov-umbrella
    #     fail_ci_if_error: true
    #     path_to_write_report: ./coverage/codecov_report.txt
    #     verbose: true
