name: Continuous Integration
on:
  pull_request:
    branches:
      - master
      - cqm_validators_2_x
      - cqm_validators_3_x

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby-version: [2.6, 2.5]
        mongodb-version: [4.0.18, 4.4]

    steps:
    - uses: actions/checkout@v2
    - name: Use Ruby ${{ matrix.ruby-version }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
    - name: Install dependencies
      run: bundle install
    - name: Start MongoDB
      uses: supercharge/mongodb-github-action@1.3.0
      with:
        mongodb-version: ${{ matrix.mongodb-version }}
    - name: Run overcommit
      run: |
        bundle exec overcommit --sign
        bundle exec overcommit --run
    - name: Run tests
      run: bundle exec rake test
